using PaymentSimulator.Api.Persistence;
// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PaymentSimulator.Api;

#nullable disable

namespace PaymentSimulator.Api.Persistence.Migrations
{
    [DbContext(typeof(PaymentDbContext))]
    [Migration("20260907154535_InitialPayments")]
    partial class InitialPayments
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.24")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PaymentSimulator.Api.PaymentOperation", b =>
                {
                    b.Property<Guid>("OperationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<int>("Requests")
                        .HasColumnType("int");

                    b.HasKey("OperationId");

                    b.ToTable("PaymentOperations", null, t =>
                        {
                            t.HasCheckConstraint("CK_PaymentOperations_Amount", "[Amount] > 0");

                            t.HasCheckConstraint("CK_PaymentOperations_Outcome", "[Outcome] IN ('Paid','Rejected','Cancelled')");
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
