// <auto-generated />
using System;
using FlashSale.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FlashSale.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(SaleDbContext))]
    [Migration("20260908122004_AlignModel")]
    partial class AlignModel
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.24")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FlashSale.Domain.Inventory", b =>
                {
                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AvailableQuantity")
                        .HasColumnType("int");

                    b.HasKey("ProductId");

                    b.ToTable("Inventory", null, t =>
                        {
                            t.HasCheckConstraint("CK_Inventory_Available", "[AvailableQuantity] >= 0");
                        });
                });

            modelBuilder.Entity("FlashSale.Domain.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)")
                        .UseCollation("Latin1_General_100_BIN2");

                    b.Property<bool>("InventoryReleased")
                        .HasColumnType("bit");

                    b.Property<string>("RequestHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nchar(64)")
                        .IsFixedLength();

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "IdempotencyKey")
                        .IsUnique();

                    b.ToTable("Orders", null, t =>
                        {
                            t.HasCheckConstraint("CK_Orders_Expiry", "[ExpiresAt] > [CreatedAt]");

                            t.HasCheckConstraint("CK_Orders_Release", "([Status] IN ('Pending','Paid') AND [InventoryReleased] = 0) OR ([Status] IN ('Failed','Expired') AND [InventoryReleased] = 1)");

                            t.HasCheckConstraint("CK_Orders_Status", "[Status] IN ('Pending','Paid','Failed','Expired')");
                        });
                });

            modelBuilder.Entity("FlashSale.Domain.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("Price")
                        .HasPrecision(11, 2)
                        .HasColumnType("decimal(11,2)");

                    b.HasKey("Id");

                    b.ToTable("Products", null, t =>
                        {
                            t.HasCheckConstraint("CK_Products_Price", "[Price] > 0");
                        });
                });

            modelBuilder.Entity("FlashSale.Infrastructure.Outbox.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Attempts")
                        .HasColumnType("int");

                    b.Property<Guid?>("LeaseToken")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("LeaseUntil")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("NextAttemptAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset")
                        .HasDefaultValueSql("SYSDATETIMEOFFSET()");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("ProcessedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("OrderId")
                        .IsUnique();

                    b.HasIndex("NextAttemptAt", "LeaseUntil")
                        .HasFilter("[ProcessedAt] IS NULL");

                    b.ToTable("OutboxMessages", null, t =>
                        {
                            t.HasCheckConstraint("CK_OutboxMessages_Attempts", "[Attempts] >= 0");

                            t.HasCheckConstraint("CK_OutboxMessages_Lease", "([LeaseToken] IS NULL AND [LeaseUntil] IS NULL) OR ([LeaseToken] IS NOT NULL AND [LeaseUntil] IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("FlashSale.Domain.Inventory", b =>
                {
                    b.HasOne("FlashSale.Domain.Product", null)
                        .WithOne()
                        .HasForeignKey("FlashSale.Domain.Inventory", "ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("FlashSale.Domain.Order", b =>
                {
                    b.OwnsMany("FlashSale.Domain.OrderItem", "Items", b1 =>
                        {
                            b1.Property<Guid>("OrderId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<Guid>("ProductId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int>("Quantity")
                                .HasColumnType("int");

                            b1.Property<decimal>("UnitPrice")
                                .HasPrecision(11, 2)
                                .HasColumnType("decimal(11,2)");

                            b1.HasKey("OrderId", "ProductId");

                            b1.HasIndex("ProductId");

                            b1.ToTable("OrderItems", null, t =>
                                {
                                    t.HasCheckConstraint("CK_OrderItems_Price", "[UnitPrice] > 0");

                                    t.HasCheckConstraint("CK_OrderItems_Quantity", "[Quantity] > 0 AND [Quantity] <= 10000");
                                });

                            b1.WithOwner()
                                .HasForeignKey("OrderId");

                            b1.HasOne("FlashSale.Domain.Product", null)
                                .WithMany()
                                .HasForeignKey("ProductId")
                                .OnDelete(DeleteBehavior.Restrict)
                                .IsRequired();
                        });

                    b.Navigation("Items");
                });

            modelBuilder.Entity("FlashSale.Infrastructure.Outbox.OutboxMessage", b =>
                {
                    b.HasOne("FlashSale.Domain.Order", null)
                        .WithOne()
                        .HasForeignKey("FlashSale.Infrastructure.Outbox.OutboxMessage", "OrderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
